# Use postgres/example user/password credentials
version: "3.9"

services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432" # "host:container"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


volumes:
  cache:
    driver: local